plugins {
    id 'java'
}

repositories {
    maven {
        url = 'https://repo.runelite.net'
    }
    mavenCentral()
}

def runeLiteVersion = 'latest.release'
def pluginMainClass = 'com.coxmegascale.CoxMegascalePlugin'

group = 'com.coxmegascale'
version = '0.1.0'

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion

    testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testImplementation group: 'org.mockito', name: 'mockito-core', version: '3.12.4'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(11)
}

tasks.register('run', JavaExec) {
    group = 'RuneLite'
    description = 'Runs RuneLite with the CoX Assistant external plugin loaded.'
    classpath = sourceSets.test.runtimeClasspath
    mainClass.set('com.coxmegascale.CoxMegascalePluginTest')
    jvmArgs = ['-ea']
}
